"""empty message

Revision ID: 4bfafc85b8fe
Revises: 87e816381d4b
Create Date: 2023-03-05 14:43:43.850331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfafc85b8fe'
down_revision = '87e816381d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_phone', ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_constraint('unique_phone', type_='unique')

    # ### end Alembic commands ###
