"""joined tables and automaticly delete children

Revision ID: ab99ad9d21c9
Revises: 4bfafc85b8fe
Create Date: 2023-03-12 17:34:37.249359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab99ad9d21c9'
down_revision = '4bfafc85b8fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_constraint('unique_phone', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_phone', ['phone'])

    # ### end Alembic commands ###
